apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        checksum/html-config: {{ include (print $.Template.BasePath "/html-configmap.yaml") . | sha256sum }}
        checksum/nginx-config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository}}:{{ .Values.image.tag }}

        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html

        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

      volumes:
      - name: html-volume
        configMap:
          name: frontend-html

      - name: nginx-config
        configMap:
          name: frontend-nginx