apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: root-app
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: examples/app-of-apps/charts/backend
    helm:
      releaseName: backend
      values: |
        replicaCount: 1
        message: "Hello from backend"
        apiVersion: "v2"
        service:
          port: 80
          targetPort: 80
        image:
          repository: nginx
          tag: latest